#!/usr/bin/env python3
"""
Generate SAURIA + Gather stimuli for the DRAM-writeback integration mode.

Flow generated by this script:

    1. Gather reads dense values and CSR/idx metadata from external DRAM.
    2. Gather writes the gathered IFMAP back to external DRAM at --gather-out-base.
    3. SAURIA starts normally and uses its standard DMA preload path to read IFMAP
       from that same DRAM address.

This is meant for the RTL configuration where gather_frontend_axi is NOT changed:

    gather_ext_mem    : gather read master, connected to external DRAM AR/R
    gather_sauria_mem : gather write master, connected to external DRAM AW/W/B

REG_AXI_WR_AW_ADDR_IN is preserved and now means external DRAM writeback address.

The script can poison the original IFMAP/out region before gather. This makes the
full SAURIA result depend on the gather writeback: if gather does not restore the
original bytes, the final SAURIA golden comparison should fail.
"""
from __future__ import annotations

import argparse
import csv
import json
from dataclasses import dataclass
from math import ceil, log2
from pathlib import Path
from typing import Iterable

# Address map
GATHER_BASE = 0x7000_0000

# Gather register offsets
REG_START                  = 0x00
REG_IS_SPMM                = 0x04
REG_DONE                   = 0x08
REG_AR_SIZE                = 0x0C
REG_AW_SIZE                = 0x10
REG_AR_ADDR_DENSE_MATRIX   = 0x14
REG_TOTAL_LEN_DENSE_MATRIX = 0x18
REG_AR_ADDR_COMP_IDX       = 0x1C
REG_TOTAL_LEN_COMP_IDX     = 0x20
REG_AR_ADDR_IDX            = 0x24
REG_TOTAL_LEN_IDX          = 0x28
REG_AXI_WR_AW_ADDR_IN      = 0x2C
REG_STATUS_REG_N_ROW       = 0x30

# SAURIA controller addresses used by the standard Verilator stimuli
CTRL_BASE       = 0x4000_0000
CTRL_START_ADDR = 0x4000_0000
CTRL_FLAGS_ADDR = 0x4000_0064   # controller args[21] in the current stimuli
CTRL_KEEP_A_BIT = 19

# Current hardware setup
AXI_BYTES = 8
ELEM_W = 16
IDX_W = 32
ELEM_BYTES = ELEM_W // 8
IDX_BYTES = IDX_W // 8

# Gather address-manager packing for FP16 on AXI64
NUM_WORDS = 128
N_BLOCKS = 8
WORDS_PER_LINE = AXI_BYTES // ELEM_BYTES     # 4 FP16 per 64-bit beat
BYTE_SEL_BITS = int(log2(WORDS_PER_LINE))    # 2
ADDR_BITS = int(log2(NUM_WORDS))             # 7


@dataclass(frozen=True)
class Range:
    name: str
    start: int
    end_excl: int

    @property
    def nbytes(self) -> int:
        return max(0, self.end_excl - self.start)

    def overlaps(self, other: "Range") -> bool:
        return self.start < other.end_excl and other.start < self.end_excl

    def fmt(self) -> str:
        if self.nbytes == 0:
            return f"{self.name}: <empty>"
        return f"{self.name}: 0x{self.start:X}..0x{self.end_excl - 1:X} ({self.nbytes} bytes)"


def gaddr(off: int) -> int:
    return GATHER_BASE + off


def nbeats(nbytes: int) -> int:
    return ceil(nbytes / AXI_BYTES)


def round_up(value: int, quantum: int) -> int:
    return ((value + quantum - 1) // quantum) * quantum


def stim_write(addr: int, data: int) -> list[int]:
    return [data & 0xFFFFFFFF, addr & 0xFFFFFFFF, 1, 0, 0, 0, 0]


def stim_read(addr: int, expected: int = 0, check: bool = False) -> list[int]:
    return [0, addr & 0xFFFFFFFF, 0, 1, 0, expected & 0xFFFFFFFF, 1 if check else 0]


def stim_wait_gather() -> list[int]:
    return [0, 0, 0, 0, 2, 0, 0]


def pack_dense_index(linear_index: int, block: int = 0) -> int:
    byte_sel = linear_index % WORDS_PER_LINE
    word_addr = linear_index // WORDS_PER_LINE
    if word_addr >= NUM_WORDS:
        raise ValueError(
            f"linear_index={linear_index} exceeds gather local NUM_WORDS={NUM_WORDS}; "
            f"try fewer values or split into blocks/tiles"
        )
    if block >= N_BLOCKS:
        raise ValueError(f"block={block} exceeds N_BLOCKS={N_BLOCKS}")
    return (block << (ADDR_BITS + BYTE_SEL_BITS)) | (word_addr << BYTE_SEL_BITS) | byte_sel


def parse_int(text: str) -> int:
    return int(text, 0)


def read_stimuli(path: Path) -> list[list[int]]:
    rows: list[list[int]] = []
    for lineno, line in enumerate(path.read_text().splitlines(), start=1):
        if not line.strip():
            continue
        vals = [int(x, 16) for x in line.split()]
        if len(vals) != 7:
            raise ValueError(f"Bad GoldenStimuli row at {path}:{lineno}: {line}")
        rows.append(vals)
    return rows


def save_stimuli(path: Path, rows: list[list[int]]) -> None:
    with path.open("w") as f:
        for row in rows:
            f.write(" ".join(f"{x:X}" for x in row) + "\n")


def read_mem(path: Path) -> list[int]:
    return [int(x.strip(), 16) for x in path.read_text().splitlines() if x.strip()]


def save_mem(path: Path, mem: list[int]) -> None:
    with path.open("w") as f:
        for b in mem:
            f.write(f"{b & 0xFF:X}\n")


def ensure_len(mem: list[int], size: int) -> None:
    if size > len(mem):
        mem.extend([0] * (size - len(mem)))


def read_bytes(mem: list[int], addr: int, nbytes: int) -> list[int]:
    ensure_len(mem, addr + nbytes)
    return mem[addr:addr + nbytes]


def write_bytes(mem: list[int], addr: int, data: Iterable[int]) -> None:
    data_list = [b & 0xFF for b in data]
    ensure_len(mem, addr + len(data_list))
    mem[addr:addr + len(data_list)] = data_list


def zero_range(mem: list[int], addr: int, nbytes: int) -> None:
    ensure_len(mem, addr + nbytes)
    mem[addr:addr + nbytes] = [0] * nbytes


def write_le(mem: list[int], addr: int, value: int, nbytes: int) -> None:
    ensure_len(mem, addr + nbytes)
    for i in range(nbytes):
        mem[addr + i] = (value >> (8 * i)) & 0xFF


def read_u32_le(mem: list[int], addr: int) -> int:
    ensure_len(mem, addr + 4)
    return sum((mem[addr + i] & 0xFF) << (8 * i) for i in range(4))


def pick_file(in_dir: Path, name: str) -> Path:
    p = in_dir / name
    if p.exists():
        return p
    matches = sorted(in_dir.glob(name.replace(".txt", "*.txt")))
    if matches:
        return matches[0]
    raise FileNotFoundError(p)


def parse_tstcfg(path: Path) -> tuple[int | None, int | None]:
    vals = [int(x.strip(), 16) for x in path.read_text().splitlines() if x.strip()]
    if len(vals) >= 3:
        return vals[1], vals[2]
    return None, None


def patch_identity_metadata(
    mem: list[int],
    comp_base: int,
    idx_base: int,
    n_values: int,
    comp_total_beats: int,
    idx_total_beats: int,
) -> None:
    # One CSR row: row_ptr-like data [0, n_values, 0].
    # Clear full AXI windows first, including padding/extra beats.
    zero_range(mem, comp_base, comp_total_beats * AXI_BYTES)
    zero_range(mem, idx_base, idx_total_beats * AXI_BYTES)

    for i, v in enumerate([0, n_values, 0]):
        write_le(mem, comp_base + i * IDX_BYTES, v, IDX_BYTES)

    for i in range(n_values):
        write_le(mem, idx_base + i * IDX_BYTES, pack_dense_index(i), IDX_BYTES)


def build_gather_rows(
    *,
    dense_base: int,
    comp_base: int,
    idx_base: int,
    gather_out_base: int,
    n_values: int,
    n_dense_cols: int,
    idx_extra_beats: int,
    check_done: bool,
) -> list[list[int]]:
    comp_count = 3
    comp_total_beats = nbeats(comp_count * IDX_BYTES)
    idx_total_beats = nbeats(n_values * IDX_BYTES) + idx_extra_beats

    return [
        stim_write(gaddr(REG_AR_SIZE), 3),
        stim_write(gaddr(REG_AW_SIZE), 3),
        stim_write(gaddr(REG_AR_ADDR_DENSE_MATRIX), dense_base),
        stim_write(gaddr(REG_TOTAL_LEN_DENSE_MATRIX), nbeats(n_dense_cols * ELEM_BYTES)),
        stim_write(gaddr(REG_AR_ADDR_COMP_IDX), comp_base),
        stim_write(gaddr(REG_TOTAL_LEN_COMP_IDX), comp_total_beats),
        stim_write(gaddr(REG_AR_ADDR_IDX), idx_base),
        stim_write(gaddr(REG_TOTAL_LEN_IDX), idx_total_beats),
        stim_write(gaddr(REG_AXI_WR_AW_ADDR_IN), gather_out_base),
        stim_write(gaddr(REG_STATUS_REG_N_ROW), n_dense_cols - 1),
        stim_write(gaddr(REG_IS_SPMM), 0),
        stim_write(gaddr(REG_START), 1),
        stim_wait_gather(),
        stim_read(gaddr(REG_DONE), 1, check=check_done),
    ]


def clear_keep_a(stim: list[list[int]]) -> bool:
    patched = False
    for row in stim:
        data, addr, we = row[0], row[1], row[2]
        if we and addr == CTRL_FLAGS_ADDR:
            row[0] = data & ~(1 << CTRL_KEEP_A_BIT)
            patched = True
            break
    return patched


def find_controller_start(stim: list[list[int]]) -> int:
    for i, row in enumerate(stim):
        data, addr, we = row[0], row[1], row[2]
        if we and addr == CTRL_START_ADDR and data == 3:
            return i
    raise RuntimeError("Could not find SAURIA controller start row: data=3 addr=0x40000000 we=1")


def first_controller_access_index(stim: list[list[int]]) -> int:
    for i, row in enumerate(stim):
        addr, we, re = row[1], row[2], row[3]
        if (we or re) and CTRL_BASE <= addr < CTRL_BASE + 0x10000:
            return i
    return 0


def validate_ranges(ranges: list[Range], check_range: Range | None, allow_overlap: bool) -> None:
    for i, r0 in enumerate(ranges):
        for r1 in ranges[i + 1:]:
            if r0.overlaps(r1):
                msg = f"Address ranges overlap: {r0.fmt()} and {r1.fmt()}"
                if allow_overlap:
                    print(f"WARNING: {msg}")
                else:
                    raise ValueError(msg + ". Use different bases or pass --allow-overlap.")
    if check_range is not None and check_range.nbytes > 0:
        for r in ranges:
            if r.name not in {"gather_out/IFMAP"} and r.overlaps(check_range):
                msg = f"Staging range overlaps final check range: {r.fmt()} vs {check_range.fmt()}"
                if allow_overlap:
                    print(f"WARNING: {msg}")
                else:
                    raise ValueError(msg + ". Move dense/CSR/idx staging above the checked output range.")


def write_expected_files(out_dir: Path, gather_out_base: int, expected_bytes: list[int]) -> None:
    # 32-bit words in the same little-endian order as debug/DRAM dumps usually show.
    with (out_dir / "expected_gather_output_words32.csv").open("w", newline="") as f:
        wr = csv.writer(f)
        wr.writerow(["word_index", "address", "expected_u32_hex"])
        for i in range(0, len(expected_bytes), 4):
            chunk = expected_bytes[i:i + 4] + [0] * max(0, 4 - len(expected_bytes[i:i + 4]))
            value = sum((chunk[j] & 0xFF) << (8 * j) for j in range(4))
            wr.writerow([i // 4, f"0x{gather_out_base + i:08X}", f"0x{value:08X}"])

    with (out_dir / "expected_gather_output_bytes.txt").open("w") as f:
        for b in expected_bytes:
            f.write(f"{b & 0xFF:X}\n")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--in-dir", required=True, help="Directory with vanilla GoldenStimuli.txt/initial_dram.txt/gold_dram.txt/tstcfg.txt")
    ap.add_argument("--out-dir", required=True, help="Output directory for generated DRAM-writeback stimuli")

    ap.add_argument("--gather-out-base", "--ifmap-base", dest="gather_out_base", type=parse_int, default=0x0,
                    help="External DRAM address where gather writes IFMAP; SAURIA must read IFMAP from this same address. Default: 0x0.")
    ap.add_argument("--dense-base", type=parse_int, default=0x90000,
                    help="Safe external DRAM staging address for dense source copied from gather-out-base. Default: 0x90000.")
    ap.add_argument("--comp-base", type=parse_int, default=0xA0000,
                    help="Safe external DRAM staging address for CSR comp_idx. Default: 0xA0000.")
    ap.add_argument("--idx-base", type=parse_int, default=0xA1000,
                    help="Safe external DRAM staging address for packed idx. Default: 0xA1000.")

    ap.add_argument("--n-values", type=int, default=340,
                    help="Number of FP16 values/nonzeros gathered and written back. Default: 340.")
    ap.add_argument("--n-dense-cols", type=int, default=340,
                    help="Dense logical columns; REG_STATUS_REG_N_ROW=n_dense_cols-1. Default: 340.")
    ap.add_argument("--idx-extra-beats", type=int, default=1,
                    help="Extra zero AXI64 beats appended to idx and included in REG_TOTAL_LEN_IDX. Default: 1.")
    ap.add_argument("--no-idx-extra-beat", action="store_true", help="Alias for --idx-extra-beats 0.")

    ap.add_argument("--poison-out", action=argparse.BooleanOptionalAction, default=True,
                    help="Poison/zero the gather output IFMAP region in initial_dram after copying it to dense staging. Default: true. This proves SAURIA depends on gather writeback.")
    ap.add_argument("--poison-value", type=parse_int, default=0x00, help="Byte value used by --poison-out. Default: 0x00.")

    ap.add_argument("--clear-keep-a", action=argparse.BooleanOptionalAction, default=True,
                    help="Clear controller keep-A bit so SAURIA uses the standard IFMAP DMA preload. Default: true.")
    ap.add_argument("--insert-position", choices=["prepend", "before-start"], default="prepend",
                    help="Where to insert gather rows. prepend = before all SAURIA config; before-start = immediately before 0x40000000 start. Default: prepend.")
    ap.add_argument("--check-gather-done", action=argparse.BooleanOptionalAction, default=True,
                    help="Use check_flag=1 when reading REG_DONE after gather. Default: true.")
    ap.add_argument("--allow-overlap", action="store_true", help="Do not error if staging/check ranges overlap; only warn.")
    ap.add_argument("--patch-gold-staging", action="store_true",
                    help="Also write dense/CSR/idx staging regions into gold_dram. Usually unnecessary when staging is outside tstcfg check range.")

    args = ap.parse_args()
    if args.no_idx_extra_beat:
        args.idx_extra_beats = 0
    if args.idx_extra_beats < 0:
        raise ValueError("--idx-extra-beats must be >= 0")
    if args.n_values <= 0 or args.n_dense_cols <= 0:
        raise ValueError("--n-values and --n-dense-cols must be positive")
    if args.n_values > args.n_dense_cols:
        raise ValueError("--n-values cannot be larger than --n-dense-cols for this identity CSR generator")

    in_dir = Path(args.in_dir)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    golden_path = pick_file(in_dir, "GoldenStimuli.txt")
    initial_path = pick_file(in_dir, "initial_dram.txt")
    gold_path = pick_file(in_dir, "gold_dram.txt")
    tstcfg_path = pick_file(in_dir, "tstcfg.txt")

    stim = read_stimuli(golden_path)
    init = read_mem(initial_path)
    gold = read_mem(gold_path)

    check_start, check_end = parse_tstcfg(tstcfg_path)
    check_range = Range("tstcfg output check", check_start, check_end) if check_start is not None and check_end is not None else None

    dense_nbytes = args.n_dense_cols * ELEM_BYTES
    gathered_nbytes = args.n_values * ELEM_BYTES
    comp_total_beats = nbeats(3 * IDX_BYTES)
    idx_natural_beats = nbeats(args.n_values * IDX_BYTES)
    idx_total_beats = idx_natural_beats + args.idx_extra_beats

    ranges = [
        Range("dense staging", args.dense_base, args.dense_base + dense_nbytes),
        Range("CSR comp_idx staging", args.comp_base, args.comp_base + comp_total_beats * AXI_BYTES),
        Range("idx staging", args.idx_base, args.idx_base + idx_total_beats * AXI_BYTES),
        Range("gather_out/IFMAP", args.gather_out_base, args.gather_out_base + gathered_nbytes),
    ]
    validate_ranges(ranges, check_range, args.allow_overlap)

    # Capture original IFMAP bytes before poisoning. These bytes are the expected
    # gather output for identity indices 0..n_values-1.
    original_dense_bytes = read_bytes(init, args.gather_out_base, dense_nbytes)
    expected_gather_bytes = original_dense_bytes[:gathered_nbytes]

    # Put dense source in a safe DRAM staging area.
    write_bytes(init, args.dense_base, original_dense_bytes)
    if args.patch_gold_staging:
        write_bytes(gold, args.dense_base, original_dense_bytes)

    # Optionally poison the original IFMAP/out region. If gather writeback fails,
    # SAURIA's normal IFMAP DMA will read this poison and the final golden check
    # should fail.
    if args.poison_out:
        write_bytes(init, args.gather_out_base, [args.poison_value & 0xFF] * gathered_nbytes)

    # Metadata goes into safe high addresses. It only needs to be present in the
    # initial memory used by the simulation. Patching gold is optional and normally
    # unnecessary when staging does not overlap the final check region.
    patch_identity_metadata(init, args.comp_base, args.idx_base, args.n_values, comp_total_beats, idx_total_beats)
    if args.patch_gold_staging:
        patch_identity_metadata(gold, args.comp_base, args.idx_base, args.n_values, comp_total_beats, idx_total_beats)

    if args.clear_keep_a:
        if not clear_keep_a(stim):
            raise RuntimeError(f"Could not find controller flags register at 0x{CTRL_FLAGS_ADDR:08X}")

    gather_rows = build_gather_rows(
        dense_base=args.dense_base,
        comp_base=args.comp_base,
        idx_base=args.idx_base,
        gather_out_base=args.gather_out_base,
        n_values=args.n_values,
        n_dense_cols=args.n_dense_cols,
        idx_extra_beats=args.idx_extra_beats,
        check_done=args.check_gather_done,
    )

    if args.insert_position == "prepend":
        insert_idx = first_controller_access_index(stim)
    else:
        insert_idx = find_controller_start(stim)
    stim = stim[:insert_idx] + gather_rows + stim[insert_idx:]

    save_stimuli(out_dir / "GoldenStimuli.txt", stim)
    save_mem(out_dir / "initial_dram.txt", init)
    save_mem(out_dir / "gold_dram.txt", gold)
    (out_dir / "tstcfg.txt").write_text(tstcfg_path.read_text())
    write_expected_files(out_dir, args.gather_out_base, expected_gather_bytes)

    manifest = {
        "mode": "gather_dram_writeback_then_sauria_dma",
        "input_files": {
            "GoldenStimuli": str(golden_path),
            "initial_dram": str(initial_path),
            "gold_dram": str(gold_path),
            "tstcfg": str(tstcfg_path),
        },
        "registers": {
            "REG_AR_SIZE": 3,
            "REG_AW_SIZE": 3,
            "REG_AR_ADDR_DENSE_MATRIX": args.dense_base,
            "REG_TOTAL_LEN_DENSE_MATRIX": nbeats(dense_nbytes),
            "REG_AR_ADDR_COMP_IDX": args.comp_base,
            "REG_TOTAL_LEN_COMP_IDX": comp_total_beats,
            "REG_AR_ADDR_IDX": args.idx_base,
            "REG_TOTAL_LEN_IDX": idx_total_beats,
            "REG_AXI_WR_AW_ADDR_IN": args.gather_out_base,
            "REG_STATUS_REG_N_ROW": args.n_dense_cols - 1,
            "REG_IS_SPMM": 0,
        },
        "ranges": {r.name: {"start": r.start, "end_exclusive": r.end_excl, "nbytes": r.nbytes} for r in ranges},
        "tstcfg_check_range": None if check_range is None else {"start": check_range.start, "end_exclusive": check_range.end_excl},
        "n_values": args.n_values,
        "n_dense_cols": args.n_dense_cols,
        "idx_natural_beats": idx_natural_beats,
        "idx_extra_beats": args.idx_extra_beats,
        "poison_out": args.poison_out,
        "poison_value": args.poison_value & 0xFF,
        "clear_keep_a": args.clear_keep_a,
        "insert_position": args.insert_position,
        "expected_first_words32": [
            f"0x{read_u32_le(expected_gather_bytes + [0, 0, 0], i):08X}"
            for i in range(0, min(len(expected_gather_bytes), 32), 4)
        ],
    }
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2))

    print(f"Wrote DRAM-writeback stimuli to {out_dir}")
    print(f"Inserted {len(gather_rows)} gather rows at stimulus index {insert_idx} ({args.insert_position})")
    print(f"Gather writes external DRAM: REG_AXI_WR_AW_ADDR_IN = 0x{args.gather_out_base:X}")
    print(f"Dense staging: 0x{args.dense_base:X}..0x{args.dense_base + dense_nbytes - 1:X}")
    print(f"CSR staging:   0x{args.comp_base:X}..0x{args.comp_base + comp_total_beats * AXI_BYTES - 1:X}")
    print(f"IDX staging:   0x{args.idx_base:X}..0x{args.idx_base + idx_total_beats * AXI_BYTES - 1:X}")
    print(f"IDX beats:     0x{idx_total_beats:X} (0x{idx_natural_beats:X} natural + {args.idx_extra_beats} extra)")
    print(f"Poison output before gather: {args.poison_out}")
    print(f"Clear keep-A: {args.clear_keep_a}")
    if check_range is not None:
        print(f"Final output check range from tstcfg: 0x{check_range.start:X}..0x{check_range.end_excl:X}")
    print("Expected gather writeback files:")
    print("  expected_gather_output_words32.csv")
    print("  expected_gather_output_bytes.txt")
    print("Final correctness: Test-Sim must end with Benchmark passed with no errors / SUCCESS.")


if __name__ == "__main__":
    main()
