// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package status_register_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 6;

  // Number of registers for every interface
  parameter int NumRegs = 13;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic        q;
  } status_register_reg2hw_start_reg_t;

  typedef struct packed {
    logic        q;
  } status_register_reg2hw_is_spmm_reg_t;

  typedef struct packed {
    logic        q;
  } status_register_reg2hw_done_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } status_register_reg2hw_ar_size_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } status_register_reg2hw_aw_size_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } status_register_reg2hw_ar_addr_dense_matrix_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } status_register_reg2hw_total_len_dense_matrix_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } status_register_reg2hw_ar_addr_comp_idx_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } status_register_reg2hw_total_len_comp_idx_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } status_register_reg2hw_ar_addr_idx_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } status_register_reg2hw_total_len_idx_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } status_register_reg2hw_axi_wr_aw_addr_in_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } status_register_reg2hw_status_reg_n_row_reg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } status_register_hw2reg_done_reg_t;

  // Register -> HW type
  typedef struct packed {
    status_register_reg2hw_start_reg_t start; // [264:264]
    status_register_reg2hw_is_spmm_reg_t is_spmm; // [263:263]
    status_register_reg2hw_done_reg_t done; // [262:262]
    status_register_reg2hw_ar_size_reg_t ar_size; // [261:259]
    status_register_reg2hw_aw_size_reg_t aw_size; // [258:256]
    status_register_reg2hw_ar_addr_dense_matrix_reg_t ar_addr_dense_matrix; // [255:224]
    status_register_reg2hw_total_len_dense_matrix_reg_t total_len_dense_matrix; // [223:192]
    status_register_reg2hw_ar_addr_comp_idx_reg_t ar_addr_comp_idx; // [191:160]
    status_register_reg2hw_total_len_comp_idx_reg_t total_len_comp_idx; // [159:128]
    status_register_reg2hw_ar_addr_idx_reg_t ar_addr_idx; // [127:96]
    status_register_reg2hw_total_len_idx_reg_t total_len_idx; // [95:64]
    status_register_reg2hw_axi_wr_aw_addr_in_reg_t axi_wr_aw_addr_in; // [63:32]
    status_register_reg2hw_status_reg_n_row_reg_t status_reg_n_row; // [31:0]
  } status_register_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    status_register_hw2reg_done_reg_t done; // [1:0]
  } status_register_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] STATUS_REGISTER_START_OFFSET = 6'h 0;
  parameter logic [BlockAw-1:0] STATUS_REGISTER_IS_SPMM_OFFSET = 6'h 4;
  parameter logic [BlockAw-1:0] STATUS_REGISTER_DONE_OFFSET = 6'h 8;
  parameter logic [BlockAw-1:0] STATUS_REGISTER_AR_SIZE_OFFSET = 6'h c;
  parameter logic [BlockAw-1:0] STATUS_REGISTER_AW_SIZE_OFFSET = 6'h 10;
  parameter logic [BlockAw-1:0] STATUS_REGISTER_AR_ADDR_DENSE_MATRIX_OFFSET = 6'h 14;
  parameter logic [BlockAw-1:0] STATUS_REGISTER_TOTAL_LEN_DENSE_MATRIX_OFFSET = 6'h 18;
  parameter logic [BlockAw-1:0] STATUS_REGISTER_AR_ADDR_COMP_IDX_OFFSET = 6'h 1c;
  parameter logic [BlockAw-1:0] STATUS_REGISTER_TOTAL_LEN_COMP_IDX_OFFSET = 6'h 20;
  parameter logic [BlockAw-1:0] STATUS_REGISTER_AR_ADDR_IDX_OFFSET = 6'h 24;
  parameter logic [BlockAw-1:0] STATUS_REGISTER_TOTAL_LEN_IDX_OFFSET = 6'h 28;
  parameter logic [BlockAw-1:0] STATUS_REGISTER_AXI_WR_AW_ADDR_IN_OFFSET = 6'h 2c;
  parameter logic [BlockAw-1:0] STATUS_REGISTER_STATUS_REG_N_ROW_OFFSET = 6'h 30;

  // Register index
  typedef enum int {
    STATUS_REGISTER_START,
    STATUS_REGISTER_IS_SPMM,
    STATUS_REGISTER_DONE,
    STATUS_REGISTER_AR_SIZE,
    STATUS_REGISTER_AW_SIZE,
    STATUS_REGISTER_AR_ADDR_DENSE_MATRIX,
    STATUS_REGISTER_TOTAL_LEN_DENSE_MATRIX,
    STATUS_REGISTER_AR_ADDR_COMP_IDX,
    STATUS_REGISTER_TOTAL_LEN_COMP_IDX,
    STATUS_REGISTER_AR_ADDR_IDX,
    STATUS_REGISTER_TOTAL_LEN_IDX,
    STATUS_REGISTER_AXI_WR_AW_ADDR_IN,
    STATUS_REGISTER_STATUS_REG_N_ROW
  } status_register_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] STATUS_REGISTER_PERMIT [13] = '{
    4'b 0001, // index[ 0] STATUS_REGISTER_START
    4'b 0001, // index[ 1] STATUS_REGISTER_IS_SPMM
    4'b 0001, // index[ 2] STATUS_REGISTER_DONE
    4'b 0001, // index[ 3] STATUS_REGISTER_AR_SIZE
    4'b 0001, // index[ 4] STATUS_REGISTER_AW_SIZE
    4'b 1111, // index[ 5] STATUS_REGISTER_AR_ADDR_DENSE_MATRIX
    4'b 1111, // index[ 6] STATUS_REGISTER_TOTAL_LEN_DENSE_MATRIX
    4'b 1111, // index[ 7] STATUS_REGISTER_AR_ADDR_COMP_IDX
    4'b 1111, // index[ 8] STATUS_REGISTER_TOTAL_LEN_COMP_IDX
    4'b 1111, // index[ 9] STATUS_REGISTER_AR_ADDR_IDX
    4'b 1111, // index[10] STATUS_REGISTER_TOTAL_LEN_IDX
    4'b 1111, // index[11] STATUS_REGISTER_AXI_WR_AW_ADDR_IN
    4'b 1111  // index[12] STATUS_REGISTER_STATUS_REG_N_ROW
  };

endpackage
