// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`

`include "prim_assert.sv"

module status_register_reg_top (
  input clk_i,
  input rst_ni,
  input  tlul_pkg::tl_h2d_t tl_i,
  output tlul_pkg::tl_d2h_t tl_o,
  // To HW
  output status_register_reg_pkg::status_register_reg2hw_t reg2hw, // Write
  input  status_register_reg_pkg::status_register_hw2reg_t hw2reg, // Read

  // Integrity check errors
  output logic intg_err_o
);

  import status_register_reg_pkg::* ;

  localparam int AW = 6;
  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;
  logic reg_busy;

  tlul_pkg::tl_h2d_t tl_reg_h2d;
  tlul_pkg::tl_d2h_t tl_reg_d2h;


  // incoming payload check
  logic intg_err;
    tlul_cmd_intg_chk u_chk (
      .tl_i(tl_i),
      .err_o(intg_err)
    );

  // also check for spurious write enables
  logic reg_we_err;
  logic [12:0] reg_we_check;
  prim_reg_we_check #(
    .OneHotWidth(13)
  ) u_prim_reg_we_check (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .oh_i  (reg_we_check),
    .en_i  (reg_we && !addrmiss),
    .err_o (reg_we_err)
  );

  logic err_q;
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      err_q <= '0;
    end else if (intg_err || reg_we_err) begin
      err_q <= 1'b1;
    end
  end

  // integrity error output is permanent and should be used for alert generation
  // register errors are transactional
  assign intg_err_o = err_q | intg_err | reg_we_err;

  // outgoing integrity generation
  tlul_pkg::tl_d2h_t tl_o_pre;
  tlul_rsp_intg_gen #(
    .EnableRspIntgGen(1),
    .EnableDataIntgGen(1)
  ) u_rsp_intg_gen (
    .tl_i(tl_o_pre),
    .tl_o(tl_o)
  );

  assign tl_reg_h2d = tl_i;
  assign tl_o_pre   = tl_reg_d2h;

  tlul_adapter_reg #(
    .RegAw(AW),
    .RegDw(DW),
    .EnableDataIntgGen(0)
  ) u_reg_if (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),

    .tl_i (tl_reg_h2d),
    .tl_o (tl_reg_d2h),

    .en_ifetch_i(prim_mubi_pkg::MuBi4False),
    .intg_error_o(),

    .we_o    (reg_we),
    .re_o    (reg_re),
    .addr_o  (reg_addr),
    .wdata_o (reg_wdata),
    .be_o    (reg_be),
    .busy_i  (reg_busy),
    .rdata_i (reg_rdata),
    .error_i (reg_error)
  );

  // cdc oversampling signals

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = addrmiss | wr_err | intg_err;

  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic start_we;
  logic start_qs;
  logic start_wd;
  logic is_spmm_we;
  logic is_spmm_qs;
  logic is_spmm_wd;
  logic done_we;
  logic done_qs;
  logic done_wd;
  logic ar_size_we;
  logic [2:0] ar_size_qs;
  logic [2:0] ar_size_wd;
  logic aw_size_we;
  logic [2:0] aw_size_qs;
  logic [2:0] aw_size_wd;
  logic ar_addr_dense_matrix_we;
  logic [31:0] ar_addr_dense_matrix_qs;
  logic [31:0] ar_addr_dense_matrix_wd;
  logic total_len_dense_matrix_we;
  logic [31:0] total_len_dense_matrix_qs;
  logic [31:0] total_len_dense_matrix_wd;
  logic ar_addr_comp_idx_we;
  logic [31:0] ar_addr_comp_idx_qs;
  logic [31:0] ar_addr_comp_idx_wd;
  logic total_len_comp_idx_we;
  logic [31:0] total_len_comp_idx_qs;
  logic [31:0] total_len_comp_idx_wd;
  logic ar_addr_idx_we;
  logic [31:0] ar_addr_idx_qs;
  logic [31:0] ar_addr_idx_wd;
  logic total_len_idx_we;
  logic [31:0] total_len_idx_qs;
  logic [31:0] total_len_idx_wd;
  logic axi_wr_aw_addr_in_we;
  logic [31:0] axi_wr_aw_addr_in_qs;
  logic [31:0] axi_wr_aw_addr_in_wd;
  logic status_reg_n_row_we;
  logic [31:0] status_reg_n_row_qs;
  logic [31:0] status_reg_n_row_wd;

  // Register instances
  // R[start]: V(False)
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_start (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (start_we),
    .wd     (start_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.start.q),
    .ds     (),

    // to register interface (read)
    .qs     (start_qs)
  );


  // R[is_spmm]: V(False)
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_is_spmm (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (is_spmm_we),
    .wd     (is_spmm_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.is_spmm.q),
    .ds     (),

    // to register interface (read)
    .qs     (is_spmm_qs)
  );


  // R[done]: V(False)
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_done (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (done_we),
    .wd     (done_wd),

    // from internal hardware
    .de     (hw2reg.done.de),
    .d      (hw2reg.done.d),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.done.q),
    .ds     (),

    // to register interface (read)
    .qs     (done_qs)
  );


  // R[ar_size]: V(False)
  prim_subreg #(
    .DW      (3),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (3'h0),
    .Mubi    (1'b0)
  ) u_ar_size (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ar_size_we),
    .wd     (ar_size_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ar_size.q),
    .ds     (),

    // to register interface (read)
    .qs     (ar_size_qs)
  );


  // R[aw_size]: V(False)
  prim_subreg #(
    .DW      (3),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (3'h0),
    .Mubi    (1'b0)
  ) u_aw_size (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (aw_size_we),
    .wd     (aw_size_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.aw_size.q),
    .ds     (),

    // to register interface (read)
    .qs     (aw_size_qs)
  );


  // R[ar_addr_dense_matrix]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_ar_addr_dense_matrix (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ar_addr_dense_matrix_we),
    .wd     (ar_addr_dense_matrix_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ar_addr_dense_matrix.q),
    .ds     (),

    // to register interface (read)
    .qs     (ar_addr_dense_matrix_qs)
  );


  // R[total_len_dense_matrix]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_total_len_dense_matrix (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (total_len_dense_matrix_we),
    .wd     (total_len_dense_matrix_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.total_len_dense_matrix.q),
    .ds     (),

    // to register interface (read)
    .qs     (total_len_dense_matrix_qs)
  );


  // R[ar_addr_comp_idx]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_ar_addr_comp_idx (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ar_addr_comp_idx_we),
    .wd     (ar_addr_comp_idx_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ar_addr_comp_idx.q),
    .ds     (),

    // to register interface (read)
    .qs     (ar_addr_comp_idx_qs)
  );


  // R[total_len_comp_idx]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_total_len_comp_idx (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (total_len_comp_idx_we),
    .wd     (total_len_comp_idx_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.total_len_comp_idx.q),
    .ds     (),

    // to register interface (read)
    .qs     (total_len_comp_idx_qs)
  );


  // R[ar_addr_idx]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_ar_addr_idx (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ar_addr_idx_we),
    .wd     (ar_addr_idx_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ar_addr_idx.q),
    .ds     (),

    // to register interface (read)
    .qs     (ar_addr_idx_qs)
  );


  // R[total_len_idx]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_total_len_idx (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (total_len_idx_we),
    .wd     (total_len_idx_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.total_len_idx.q),
    .ds     (),

    // to register interface (read)
    .qs     (total_len_idx_qs)
  );


  // R[axi_wr_aw_addr_in]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_axi_wr_aw_addr_in (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (axi_wr_aw_addr_in_we),
    .wd     (axi_wr_aw_addr_in_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.axi_wr_aw_addr_in.q),
    .ds     (),

    // to register interface (read)
    .qs     (axi_wr_aw_addr_in_qs)
  );


  // R[status_reg_n_row]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_status_reg_n_row (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (status_reg_n_row_we),
    .wd     (status_reg_n_row_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.status_reg_n_row.q),
    .ds     (),

    // to register interface (read)
    .qs     (status_reg_n_row_qs)
  );



  logic [12:0] addr_hit;
  always_comb begin
    addr_hit[ 0] = (reg_addr == STATUS_REGISTER_START_OFFSET);
    addr_hit[ 1] = (reg_addr == STATUS_REGISTER_IS_SPMM_OFFSET);
    addr_hit[ 2] = (reg_addr == STATUS_REGISTER_DONE_OFFSET);
    addr_hit[ 3] = (reg_addr == STATUS_REGISTER_AR_SIZE_OFFSET);
    addr_hit[ 4] = (reg_addr == STATUS_REGISTER_AW_SIZE_OFFSET);
    addr_hit[ 5] = (reg_addr == STATUS_REGISTER_AR_ADDR_DENSE_MATRIX_OFFSET);
    addr_hit[ 6] = (reg_addr == STATUS_REGISTER_TOTAL_LEN_DENSE_MATRIX_OFFSET);
    addr_hit[ 7] = (reg_addr == STATUS_REGISTER_AR_ADDR_COMP_IDX_OFFSET);
    addr_hit[ 8] = (reg_addr == STATUS_REGISTER_TOTAL_LEN_COMP_IDX_OFFSET);
    addr_hit[ 9] = (reg_addr == STATUS_REGISTER_AR_ADDR_IDX_OFFSET);
    addr_hit[10] = (reg_addr == STATUS_REGISTER_TOTAL_LEN_IDX_OFFSET);
    addr_hit[11] = (reg_addr == STATUS_REGISTER_AXI_WR_AW_ADDR_IN_OFFSET);
    addr_hit[12] = (reg_addr == STATUS_REGISTER_STATUS_REG_N_ROW_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[ 0] & (|(STATUS_REGISTER_PERMIT[ 0] & ~reg_be))) |
               (addr_hit[ 1] & (|(STATUS_REGISTER_PERMIT[ 1] & ~reg_be))) |
               (addr_hit[ 2] & (|(STATUS_REGISTER_PERMIT[ 2] & ~reg_be))) |
               (addr_hit[ 3] & (|(STATUS_REGISTER_PERMIT[ 3] & ~reg_be))) |
               (addr_hit[ 4] & (|(STATUS_REGISTER_PERMIT[ 4] & ~reg_be))) |
               (addr_hit[ 5] & (|(STATUS_REGISTER_PERMIT[ 5] & ~reg_be))) |
               (addr_hit[ 6] & (|(STATUS_REGISTER_PERMIT[ 6] & ~reg_be))) |
               (addr_hit[ 7] & (|(STATUS_REGISTER_PERMIT[ 7] & ~reg_be))) |
               (addr_hit[ 8] & (|(STATUS_REGISTER_PERMIT[ 8] & ~reg_be))) |
               (addr_hit[ 9] & (|(STATUS_REGISTER_PERMIT[ 9] & ~reg_be))) |
               (addr_hit[10] & (|(STATUS_REGISTER_PERMIT[10] & ~reg_be))) |
               (addr_hit[11] & (|(STATUS_REGISTER_PERMIT[11] & ~reg_be))) |
               (addr_hit[12] & (|(STATUS_REGISTER_PERMIT[12] & ~reg_be)))));
  end

  // Generate write-enables
  assign start_we = addr_hit[0] & reg_we & !reg_error;

  assign start_wd = reg_wdata[0];
  assign is_spmm_we = addr_hit[1] & reg_we & !reg_error;

  assign is_spmm_wd = reg_wdata[0];
  assign done_we = addr_hit[2] & reg_we & !reg_error;

  assign done_wd = reg_wdata[0];
  assign ar_size_we = addr_hit[3] & reg_we & !reg_error;

  assign ar_size_wd = reg_wdata[2:0];
  assign aw_size_we = addr_hit[4] & reg_we & !reg_error;

  assign aw_size_wd = reg_wdata[2:0];
  assign ar_addr_dense_matrix_we = addr_hit[5] & reg_we & !reg_error;

  assign ar_addr_dense_matrix_wd = reg_wdata[31:0];
  assign total_len_dense_matrix_we = addr_hit[6] & reg_we & !reg_error;

  assign total_len_dense_matrix_wd = reg_wdata[31:0];
  assign ar_addr_comp_idx_we = addr_hit[7] & reg_we & !reg_error;

  assign ar_addr_comp_idx_wd = reg_wdata[31:0];
  assign total_len_comp_idx_we = addr_hit[8] & reg_we & !reg_error;

  assign total_len_comp_idx_wd = reg_wdata[31:0];
  assign ar_addr_idx_we = addr_hit[9] & reg_we & !reg_error;

  assign ar_addr_idx_wd = reg_wdata[31:0];
  assign total_len_idx_we = addr_hit[10] & reg_we & !reg_error;

  assign total_len_idx_wd = reg_wdata[31:0];
  assign axi_wr_aw_addr_in_we = addr_hit[11] & reg_we & !reg_error;

  assign axi_wr_aw_addr_in_wd = reg_wdata[31:0];
  assign status_reg_n_row_we = addr_hit[12] & reg_we & !reg_error;

  assign status_reg_n_row_wd = reg_wdata[31:0];

  // Assign write-enables to checker logic vector.
  always_comb begin
    reg_we_check[0] = start_we;
    reg_we_check[1] = is_spmm_we;
    reg_we_check[2] = done_we;
    reg_we_check[3] = ar_size_we;
    reg_we_check[4] = aw_size_we;
    reg_we_check[5] = ar_addr_dense_matrix_we;
    reg_we_check[6] = total_len_dense_matrix_we;
    reg_we_check[7] = ar_addr_comp_idx_we;
    reg_we_check[8] = total_len_comp_idx_we;
    reg_we_check[9] = ar_addr_idx_we;
    reg_we_check[10] = total_len_idx_we;
    reg_we_check[11] = axi_wr_aw_addr_in_we;
    reg_we_check[12] = status_reg_n_row_we;
  end

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = start_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[0] = is_spmm_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[0] = done_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[2:0] = ar_size_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[2:0] = aw_size_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[31:0] = ar_addr_dense_matrix_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[31:0] = total_len_dense_matrix_qs;
      end

      addr_hit[7]: begin
        reg_rdata_next[31:0] = ar_addr_comp_idx_qs;
      end

      addr_hit[8]: begin
        reg_rdata_next[31:0] = total_len_comp_idx_qs;
      end

      addr_hit[9]: begin
        reg_rdata_next[31:0] = ar_addr_idx_qs;
      end

      addr_hit[10]: begin
        reg_rdata_next[31:0] = total_len_idx_qs;
      end

      addr_hit[11]: begin
        reg_rdata_next[31:0] = axi_wr_aw_addr_in_qs;
      end

      addr_hit[12]: begin
        reg_rdata_next[31:0] = status_reg_n_row_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // shadow busy
  logic shadow_busy;
  assign shadow_busy = 1'b0;

  // register busy
  assign reg_busy = shadow_busy;

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT_PULSE(wePulse, reg_we, clk_i, !rst_ni)
  `ASSERT_PULSE(rePulse, reg_re, clk_i, !rst_ni)

  `ASSERT(reAfterRv, $rose(reg_re || reg_we) |=> tl_o_pre.d_valid, clk_i, !rst_ni)

  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit), clk_i, !rst_ni)

  // this is formulated as an assumption such that the FPV testbenches do disprove this
  // property by mistake
  //`ASSUME(reqParity, tl_reg_h2d.a_valid |-> tl_reg_h2d.a_user.chk_en == tlul_pkg::CheckDis)

endmodule
